# Generated by Django 5.1.2 on 2024-10-25 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_tag_project_vote_ration_project_vote_total_review_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='vote_ration',
            new_name='vote_ratio',
        ),
    ]
